ArgonneCPAC/diffsky

- .github/workflows/tests.yml
- diffsky/tests/test_diffsky_setup.py
- requirements.txt
PR brings in unit testing workflow
> Add CI testing github action

- .readthedocs.yml
- docs/Makefile
- docs/make.bat
- docs/source/citation.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/requirements.txt
- requirements.txt
- setup.py
Basic skeleton setup for readthedocs
> Docs config

- README.rst
Update readme with link to rtd
> Update readme with link to rtd

- .github/workflows/tests.yml
Add codecov upload to tests.yml
> Add codecov upload to tests.yml

- .github/workflows/tests.yml
- diffsky/tests/test_utils.py
- diffsky/utils.py
> Add utils module

- diffsky/experimental/janeane/photpop.py
Switch to ssp_lg_age_gyr for consistency with dsps
> Change ssp_lg_age to ssp_lg_age_gyr in photpop.py

- .github/workflows/linting.yml
Separate linting and unit tests in github workflows
> Separate linting and unit tests in github workflows

- diffsky/experimental/dspspop/boris_dust.py
- diffsky/experimental/dspspop/burstshapepop.py
- diffsky/experimental/dspspop/dustpop.py
- diffsky/experimental/dspspop/flexburst.py
- diffsky/experimental/dspspop/lgfburstpop.py
- diffsky/experimental/dspspop/nagaraj22_dust.py
- diffsky/experimental/dspspop/photpop.py
- diffsky/experimental/dspspop/tests/test_burstshapepop.py
- diffsky/experimental/dspspop/tests/test_flexburst.py
- diffsky/experimental/dspspop/tests/test_lgfburstpop.py
- diffsky/experimental/dspspop/tests/test_photpop.py
> Add dspspop subdir

- diffsky/diffndhist.py
- diffsky/tests/test_diffndhist.py
Add module to compute triweight histograms in n-dimensions
cc @gbeltzmo
> Add diffndhist.py

- diffsky/experimental/dspspop/burstshapepop.py
- diffsky/experimental/dspspop/dust_deltapop.py
Widened bounds on dust parameters delta and also burst shape parameters
> Widened bounds on dust parameters delta and also burst shape parameters

- diffsky/experimental/dspspop/tests/test_burstshapepop.py
Bug-fix PR for unit test failure
> Require 0.1% accuracy for DiffburstPop model

- .readthedocs.yml
- docs/source/conf.py
- docs/source/requirements.txt
- docs/source/rtd_environment.yaml
Use conda yaml to manage RTD environment
> Use conda yaml to manage RTD environment

- README.rst
- docs/source/installation.rst
Update installation instructions
> Update installation instructions

- pyproject.toml
infer dependencies from requirements.txt from within pyproject.toml
> infer dependencies from requirements.txt from within pyproject.toml

- .github/workflows/tests.yml
- diffsky/experimental/dspspop/burstshapepop.py
- diffsky/experimental/dspspop/photpop.py
- diffsky/experimental/dspspop/tests/test_burstshapepop.py
- diffsky/tests/test_diffsky_setup.py
Bring diffsky up-to-date with dsps v0.3.7
> Bring diffsky up-to-date with dsps v0.3.7

- diffsky/burstpop/__init__.py
- diffsky/dustpop/__init__.py
- diffsky/sbl18_photgrad.py
- diffsky/tests/test_sbl18_photgrad.py
- diffsky/tw_photgrad.py
Add get_bounded_spspop_params and get_unbounded_spspop_params functions
> Add get_bounded_spspop_params and get_unbounded_spspop_params functions

- .github/workflows/monthly-warning-test.yml
Add CI workflow testing if any warnings are raised
> Add CI workflow testing if any warnings are raised

- diffsky/mass_functions/mc_subhalo_catalog.py
- diffsky/mass_functions/tests/test_mc_subhalo_catalog.py
> Add mc_subhalo_catalog module

- diffsky/experimental/dspspop/burstshapepop.py
- diffsky/experimental/dspspop/dust_deltapop.py
- diffsky/experimental/dspspop/lgavpop.py
- diffsky/experimental/dspspop/lgfburstpop.py
- diffsky/mass_functions/mc_tinfall.py
- diffsky/mass_functions/utils.py
- diffsky/utils.py
jax.lax.logistic-->jax.nn.sigmoid
> jax.lax.logistic-->jax.nn.sigmoid

- diffsky/mass_functions/mc_tinfall.py
- diffsky/mass_functions/tests/test_mc_tinfall.py
Deterministic behavior of Monte Carlo realizations of t_infall
> Deterministic behavior of Monte Carlo realizations of t_infall

- diffsky/mass_functions/mc_subhalo_catalog.py
Fix bug in t_penultimate_infall and t_ultimate_infall returned by mc_subhalo_catalog_singlez
> Fix bug in t_penultimate_infall and t_ultimate_infall returned by mc_subhalo_catalog_singlez

- diffsky/burstpop/diffqburstpop.py
- diffsky/burstpop/freqburst.py
- diffsky/burstpop/tests/test_diffqburstpop.py
Add DEFAULT_FREQBURST_PARAMS to DiffburstPopParams
> Add DEFAULT_FREQBURST_PARAMS to DiffburstPopParams

- .github/workflows/monthly-warning-test.yml
- .github/workflows/tests.yml
- .github/workflows/tests_cron.yml
- diffsky/dustpop/diagnostics/plot_funopop_simple.py
- diffsky/dustpop/diagnostics/tests/test_plot_funopop_simple.py
Some example plots generated by this code for a few randomly generated models:
> Add diagnostic plots of `funopop_simple`

- diffsky/burstpop/diagnostics/plot_fburstpop.py
- diffsky/burstpop/diagnostics/tests/test_plot_fburstpop.py
Some example plots generated by this code for a few randomly generated models:
> Add lgFburst diagnostic

- diffsky/mass_functions/fitting_utils/fit_hmf_model.py
- diffsky/mass_functions/fitting_utils/tests/test_fit_hmf_model.py
- diffsky/mass_functions/hmf_model.py
- diffsky/mass_functions/mc_hosts.py
- diffsky/mass_functions/tests/test_hmf_model.py
Rename predict_hmf --> predict_cuml_hmf
> Rename predict_hmf --> predict_cuml_hmf

- diffsky/dustpop/tests/test_avpop_mono.py
New unit test of AvPop walks around the u-parameter space of AvPop, and for each point in u-param pop space, the test computes Av for 5,000 wildly different galaxies, and enforces that `av_min=0.02 < av < av_max=2.5`.
> Add new test of AvPop

- diffsky/mass_functions/tests/test_measure_hmf.py
> np.in1d --> np.isin to avoid deprecation warning

- diffsky/sumstats/diffndhist.py
- diffsky/sumstats/smhm.py
- diffsky/sumstats/tests/test_smhm.py
Add measurements directory for common sumstats
> Add measurements directory for common sumstats

- diffsky/mass_functions/smhm_kernels/tests/test_threeroll_smhm.py
- diffsky/mass_functions/smhm_kernels/threeroll_kernels.py
- diffsky/mass_functions/smhm_kernels/threeroll_smhm.py
> Add smhm_kernels sub-package

- diffsky/mass_functions/upweighting/namedtuple_cat_utils.py
- diffsky/mass_functions/upweighting/tests/test_mc_gen_upweighting.py
- diffsky/mass_functions/upweighting/upweighting.py
Add upweighting subpackage and tests
> Add upweighting subpackage and tests

- CHANGES.rst
- diffsky/mass_functions/mc_diffmah_tpeak.py
- diffsky/mass_functions/upweighting/tests/test_mc_gen_upweighting.py
- docs/source/demo_diffmahpop_t_peak.ipynb
- requirements.txt
Update mc_diffmah_tpeak to use the new 5-parameter diffmah introduced in [this PR](https://github.com/ArgonneCPAC/diffmah/pull/147)
> Update mc_diffmah_tpeak to use the new 5-parameter diffmah

- docs/source/rtd_environment.yaml
- requirements.txt
> Require dsps>=0.4.0

- diffsky/data_loaders/load_discovery_cores.py
Bug fix for discovery data loader
> Add diffmah data_loader

- diffsky/data_loaders/hacc_core_utils.py
Add optional kwarg keys to load_flat_hdf5
> Add optional kwarg keys to load_flat_hdf5

- diffsky/burstpop/diagnostics/plot_tburstpop.py
- diffsky/burstpop/diagnostics/tests/test_plot_tburstpop.py
This PR brings in a module that makes this diagnostic plot
@gbeltzmo
> Add new diagnostic for tburstpop

- diffsky/data_loaders/hacc_core_utils.py
- diffsky/data_loaders/tests/test_hacc_core_utils.py
Add get_timestep_range_from_z_range function
> Add get_timestep_range_from_z_range function

- diffsky/data_loaders/load_hacc_cores.py
- diffsky/data_loaders/tests/test_load_hacc_cores.py
- scripts/make_sfh_lj_mock.py
Clean up data loader for hacc sims
> Data loader cleanup

- .github/workflows/monthly-warning-test.yaml
- .github/workflows/test_latest_releases.yaml
- .github/workflows/test_main_branch.yaml
- .github/workflows/tests_cron.yaml
- diffsky/cosmos_utils/cosmos_mstar_model.py
- diffsky/cosmos_utils/tests/test_cosmos_mstar_model.py
- diffsky/data_loaders/cosmos20_loader.py
- diffsky/data_loaders/tests/test_cosmos_loader.py
- diffsky/data_loaders/tests/testing_data/cosmos20_shasum.dat
Migrate cosmos20_loader.py from the https://github.com/LSSTDESC/cosmos20_colors repository into `data_loaders` package.
Closes #96
> Add `cosmos20_loader.py` to `data_loaders` package

- diffsky/mass_functions/mc_diffmah_tpeak.py
- diffsky/mass_functions/tests/test_mc_diffmah_tpeak.py
Add option to pass in grid of halo masses into MC subcat generator
> Add option to pass in grid of halo masses into MC subcat generator

- diffsky/mc_diffsky.py
- diffsky/tests/test_mc_diffsky.py
Add `mc_diffstar_galhalo_pop` to new module `mc_diffsky.py`
> Mc diffstar

- diffsky/diagnostics/plot_diffstar_fq.py
- diffsky/diagnostics/tests/test_plot_diffstar_fq.py
This PR brings in code that makes this plot.
> Add diagnostic plotter for diffstarpop quenched fraction

- diffsky/diagnostics/plot_diffstar_fq.py
- diffsky/mc_diffsky.py
Update default diffstarpop parameters according to https://github.com/ArgonneCPAC/diffstarpop/pull/46
> Update default diffstarpop parameters

- diffsky/experimental/phot_utils.py
- diffsky/experimental/precompute_ssp_phot.py
- diffsky/experimental/tests/test_precompute_ssp_phot.py
Add precompute_ssp_phot.py module
> Add precompute_ssp_phot.py module

- diffsky/experimental/precompute_ssp_phot.py
Add docstrings to precompute_ssp_phot.py
> Add docstrings to precompute_ssp_phot.py

- diffsky/dustpop/tests/test_tw_dustpop_mono.py
- diffsky/dustpop/tw_dustpop_mono.py
This adds a container model for the latest dust model used by @gbeltzmo
> Add new module `tw_dustpop_mono.py` 

- diffsky/dustpop/tests/test_tw_dustpop_mono.py
- diffsky/dustpop/tests/test_tw_dustpop_mono_noise.py
- diffsky/dustpop/tw_dustpop_mono.py
- diffsky/dustpop/tw_dustpop_mono_noise.py
Add module for including noise in dust
> Add module for including noise in dust

- diffsky/dustpop/tests/test_tw_dustpop_mono.py
- diffsky/dustpop/tests/test_tw_dustpop_mono_noise.py
- diffsky/dustpop/tw_dustpop_mono.py
- diffsky/dustpop/tw_dustpop_mono_noise.py
- diffsky/experimental/mc_diffsky_phot.py
Update Monte Carlo generator of Diffsky photometry to use `tw_dustpop_mono_noise`
> Update Monte Carlo generator of Diffsky photometry to use `tw_dustpop_mono_noise`

- .github/workflows/linting.yaml
Add flake8-pyproject to linting.yaml conda env
> Add flake8-pyproject to linting.yaml conda env

- diffsky/data_loaders/load_hacc_cores.py
- diffsky/data_loaders/tests/test_load_hacc_cores.py
Improve flexibility to load_diffsky_data include_fields kwarg
> Improve flexibility to load_diffsky_data include_fields kwarg

- diffsky/burstpop/freqburst_mono.py
- diffsky/burstpop/tests/test_freqburst_mono.py
Adopt less conservative bounds on the burst frequency
> Change bounds on freqburst_mono.py

- diffsky/ssp_err_model/ssp_err_model.py
- diffsky/ssp_err_model/tests/test_ssp_err_model.py
> Add ssp_err_model

- diffsky/data_loaders/load_hacc_cores.py
- diffsky/data_loaders/tests/test_load_hacc_cores.py
Add concatenate_diffsky_subcats function
> Add concatenate_diffsky_subcats function

- diffsky/data_loaders/load_hacc_cores.py
Fix bug in load_subcat_from_disk
> Fix bug in load_subcat_from_disk

- diffsky/data_loaders/hacc_core_utils.py
Fix bug in `get_timestep_range_from_z_range`
> Fix bug in `get_timestep_range_from_z_range`

- diffsky/data_loaders/hacc_utils/defaults.py
- diffsky/data_loaders/hacc_utils/lightcone_utils.py
- scripts/lc_cf_crossmatch_script.py
Parallelize HACC lightcone utils
> Parallelize HACC lightcone utils

- diffsky/__init__.py
- diffsky/diagnostics/plot_delta_mag_burstiness.py
- diffsky/dustpop/sbl18_dust_kernels.py
- diffsky/dustpop/tw_dust_kernels.py
- diffsky/sbl18_photgrad.py
- diffsky/ssp_err_model/ssp_err_model.py
- diffsky/tw_photgrad.py
- diffsky/utils/__init__.py
- diffsky/utils/tests/test_tw_utils.py
- diffsky/utils/tw_utils.py
Move `tw_utils.py` into `diffsky/utils`
> Move `tw_utils.py` into `diffsky/utils`

- diffsky/mass_functions/mc_hosts.py
- diffsky/mass_functions/tests/test_mc_diffmah_tpeak.py
- diffsky/mass_functions/tests/test_mc_hosts.py
Refactor mc_hosts to simplify extending to low mass
> Refactor mc_hosts to simplify extending to low mass

- diffsky/experimental/mc_lightcone_halos.py
- diffsky/experimental/tests/test_mc_lightcone_halos.py
Also fix little h in the lightcone generator. And develop skeleton for mc_lightcone_extension function.
> Add lgmp_max feature to halo mass function generation

- diffsky/experimental/tests/test_mc_lightcone_halos.py
- diffsky/mass_functions/fitting_utils/calibrations/hacc_core_shmf_params.py
- diffsky/mass_functions/fitting_utils/calibrations/tests/test_hacc_core_shmf_params.py
Add calibration of unevolved subhalo mass function
> Add calibration of unevolved subhalo mass function

- requirements.txt
Update requirements: `diffmah>=0.7.2` and `dsps>=0.4.5`
> Update diffmah and dsps requirements

- .github/workflows/monthly-warning-test.yaml
- .github/workflows/test_latest_releases.yaml
- .github/workflows/test_main_branch.yaml
- .github/workflows/tests_cron.yaml
Update diffstarpop to main in CI workflows
> Update diffstarpop to main in CI workflows

- .gitignore
- diffsky/data_loaders/hacc_utils/lc_mock_production.py
- diffsky/data_loaders/hacc_utils/lightcone_utils.py
- diffsky/data_loaders/hacc_utils/load_lc_cf.py
- diffsky/data_loaders/hacc_utils/load_lc_mock.py
- diffsky/data_loaders/hacc_utils/tests/test_lc_mock_production.py
- diffsky/data_loaders/hacc_utils/tests/test_load_lc_cf.py
- diffsky/utils/sfh_utils.py
- diffsky/utils/tests/test_sfh_utils.py
- scripts/JOBS/run_sfh_mock_serial.sh
- scripts/make_sfh_lc_mock_lj_serial.py
- scripts/make_sfh_lightcone_last_journey.py
Add lightcone mock production script
> Add lightcone mock production script

- diffsky/fake_sats/ellipsoidal_nfw_phase_space.py
- diffsky/fake_sats/ellipsoidal_velocities.py
- diffsky/fake_sats/nfw_config_space.py
- diffsky/fake_sats/rotations3d.py
- diffsky/fake_sats/tests/test_ellipsoidal_nfw_phase_space.py
- diffsky/fake_sats/tests/test_mc_ellipticial_velocities.py
- diffsky/fake_sats/tests/test_nfw_config_space.py
- diffsky/fake_sats/tests/test_rotations3d.py
- diffsky/fake_sats/vector_utilities.py
Add `fake_sats` sub-package for assigning satellite position and velocity
> Add `fake_sats` sub-package for assigning satellite position and velocity

- diffsky/data_loaders/hacc_utils/data_validation/tests/test_validate_lc_cores.py
- diffsky/data_loaders/hacc_utils/data_validation/validate_lc_cores.py
Add validation test of `lc_cores` that `top_host_tag` is consistent with `top_host_idx`
> Add validation test of `lc_cores` that `top_host_tag` is consistent with `top_host_idx`

- diffsky/data_loaders/hacc_utils/load_lc_cf.py
- diffsky/data_loaders/hacc_utils/load_lc_cf_synthetic.py
- scripts/make_sfh_lc_mock_lj_serial.py
Add synthetic galaxies to lightcone mock production pipeline
> Add synthetic galaxies to lightcone mock production pipeline

- diffsky/data_loaders/hacc_utils/metadata_sfh_mock.py
Store diffstarpop version in diffsky metadata
> Store diffstarpop version in diffsky metadata

- diffsky/data_loaders/hacc_utils/data_validation/tests/test_validate_lc_cores.py
- diffsky/data_loaders/hacc_utils/data_validation/validate_lc_cores.py
Add unit test that host position is close to galaxy position in `lc_cores`
> Add unit test that host position is close to galaxy position in `lc_cores`

- diffsky/data_loaders/hacc_utils/lc_mock_production.py
- diffsky/data_loaders/hacc_utils/load_lc_cf.py
- diffsky/data_loaders/hacc_utils/load_lc_cf_synthetic.py
- diffsky/data_loaders/hacc_utils/metadata_sfh_mock.py
> `z_true --> redshift_true`

- diffsky/data_loaders/hacc_utils/lc_mock_production.py
- diffsky/data_loaders/hacc_utils/lightcone_utils.py
- diffsky/data_loaders/hacc_utils/metadata_sfh_mock.py
- scripts/lc_cf_crossmatch_script.py
Add peculiar velocity and halo shape to output lightcone mock
> Add peculiar velocity and halo shape to output lightcone mock

- diffsky/data_loaders/io_utils.py
Fix bug in keys feature of load_flat_hdf5
> Load flat hdf5 bugfix

- diffsky/mass_functions/fitting_utils/fit_flat_hmf_model.py
- diffsky/mass_functions/fitting_utils/tests/test_fit_flat_hmf_model.py
- diffsky/mass_functions/flat_hmf_model.py
- diffsky/mass_functions/tests/test_flat_hmf_model.py
Add `flat_hmf_model.py` with flattened namedtuple parameters
@georgezch
> Add `flat_hmf_model.py` with flattened namedtuple parameters

- diffsky/data_loaders/hacc_utils/lightcone_utils.py
- scripts/LJ_LC_JOBS/make_sfh_lc_mock_lj.py
- scripts/lc_cf_crossmatch_script.py
- scripts/make_sfh_lightcone_last_journey.py
- scripts/tabulate_coreforest_overlap.py
Fix indexing bug in lightcone mocks
> Fix indexing bug in lightcone mocks

- scripts/LJ_CROSSX/run_tabulate_coreforest_overlap.sh
Add example job script for overlap tabulation
> Add example job script for overlap tabulation

- diffsky/experimental/mc_lightcone_halos.py
- diffsky/experimental/tests/test_sobol_lightcone.py
- docs/source/demo_diffstarpop.ipynb
- docs/source/demo_mc_lightcones.ipynb
- docs/source/demos.rst
Includes both diffmah and diffstar kernels
> Implement sobol lightcone

- CHANGES.rst
> Update changelog for v0.2.5

- .github/workflows/monthly-warning-test.yaml
- .github/workflows/test_main_branch.yaml
- .github/workflows/tests_cron.yaml
- diffsky/data_loaders/hacc_utils/lc_mock_production.py
- diffsky/diagnostics/plot_delta_mag_burstiness.py
- diffsky/diagnostics/plot_diffstar_fq.py
- diffsky/experimental/diagnostics/check_smhm.py
- diffsky/experimental/lc_phot_kern.py
- diffsky/experimental/mc_diffsky_phot.py
- diffsky/experimental/mc_diffsky_seds.py
- diffsky/experimental/mc_lightcone_halos.py
- diffsky/experimental/tests/test_lc_phot_kern.py
- diffsky/experimental/tests/test_mc_diffsky_seds.py
- diffsky/experimental/tests/test_mc_lightcone_halos.py
- diffsky/experimental/tests/test_sobol_lightcone.py
- diffsky/mc_diffsky.py
- diffsky/param_utils/diffsky_param_wrapper.py
- diffsky/param_utils/tests/test_diffsky_param_wrapper.py
- docs/source/rtd_environment.yaml
- requirements.txt
This WIP PR updates `diffsky` to be compatible with `v1.0.0` release of `diffstar`.
> Diffstar v1p0 update

- CHANGES.rst
- README.rst
- requirements.txt
> Update to `diffstar>=1.0.0`
