ArgonneCPAC/diffsky

- diffsky/experimental/photometry_interpolation.py
- diffsky/experimental/tests/test_photometry_interpolation.py
- requirements.txt
This PR brings in an updated version of the photometry interpolation kernels currently being used by lsstdesc-diffsky. The API of this new kernel is not yet stable and so the new module has been placed in `diffsky.experimental`.
> Add photometry_interpolation.py module to new experimental subdrn

- diffsky/experimental/dspspop/dust_deltapop.py
- diffsky/experimental/dspspop/dustpop.py
- diffsky/experimental/dspspop/lgavpop.py
- diffsky/experimental/dspspop/photpop.py
- diffsky/experimental/dspspop/tests/test_attavpop.py
- diffsky/experimental/dspspop/tests/test_dustdeltapop.py
- diffsky/experimental/dspspop/tests/test_photpop.py
@gbeltzmo this PR implements sigmoid-type models of the attenuation curve parameters Av and δ. All SPS parameters accepted by `dust.get_obs_photometry_singlez` are now bounded. And the Av model no longer depends on redshift.
> single-redshift dust attenuation models

- diffsky/diffndhist.py
This PR removes a few obsolete kernels and adds some in-line comments to explain how the vmapping works for the `tw_ndhist` function
> Document how the tw_ndhist kernel is built

- diffsky/diffndhist.py
- diffsky/tests/test_diffndhist.py
The diffndhist module now contains a new kernel, `tw_ndhist_weighted`, that facilitates calculation of quantities such as 
`<y | x0, x0, ..., x2>`. This new kernel works in the same way as `tw_ndhist` in that the N-dimensional points stored in the input `nddata` will be differentiably histogrammed using the triweight trick, only `tw_ndhist_weighted` will sum up `w*y` whereas `tw_ndhist` only summed `w`. Thus dividing the result of `tw_ndhist_weighted` by the result of `tw_ndhist` calculates `<y | x0, x0, ..., x2>`.
@gbeltzmo I'm not sure whether you will want to use this new kernel `tw_ndhist_weighted` or stick with just `tw_ndhist`, it depends on what sumstat you choose. For example, maybe we decide that for our sumstats we want to stick with generalized abundance functions, such as the …
> Add tw_ndhist_weighted kernel to diffndhist module

- .github/workflows/tests_cron.yml
With every PR, we now have two separate workflows that run our test suite in different environment configurations:
1. Using the latest releases of all the Diff+ codes in our dependency chain
2. Using the current main branch of all the Diff+ codes in our dependency chain
In addition to tests triggered by a PR, tests with environment config (2) are now part of a cron job that runs this workflow twice a week (early in the morning every Monday and Thursday). This new cron should help make sure we notice when changes to the main branch of one of the Diff+ codes has downstream consequences for this repo.
See https://github.com/LSSTDESC/lsstdesc-diffsky/pull/59 for the analogous implementation in lsstdesc-diffsky.
> Add weekly cron

- diffsky/dustpop/sbl18_dust_kernels.py
The sbl18_dust_transmission was incorrectly implemented. This PR resolves the bug. Probably the SBL18 kernels can simply go away in future, but for present purposes this PR keeps everything the same besides the bug-fix.
> Sbl18 bugfix

- diffsky/mass_functions/hmf_model.py
Refactor hmf code to independently compute single-redshift HMFParams. This simplifies a downstream calculation of the differential mass function at a single redshift.
> Refactor hmf code to independently compute single-redshift HMFParams

- diffsky/tests/test_dependencies.py
These two packages each implement a clip at SFR_MIN, but neither package depends on the other. Diffsky depends on both, and so this test is natural to enforce here.
> Add consistency test of SFR_MIN between dsps and diffstar

- diffsky/mass_functions/__init__.py
- diffsky/mass_functions/hmf_model.py
- diffsky/mass_functions/tests/test_mc_hosts.py
The `predict_differential_hmf` function is computed in terms of the gradient of the cumulative halo mass function `predict_cuml_hmf`.
The plot below visualizes a new unit test. To make the orange curve, we generate a Monte Carlo realization of the host halo population, a computation that uses the _cumulative_ halo mass function in the MC generation, and then use a histogram with hard-edged bins to estimate the differential HMF. To make the blue curve, we call the new analytical function, which is implemented by using `jax.grad` on the mass variable of the differential function. So this new unit test ensures self-consistency between the cumulative and differential implementations mass function implementations.
> Add analytical calculator for the differential halo mass function `predict_differential_hmf`

- diffsky/dustpop/avpop_mono.py
- diffsky/dustpop/tests/test_avpop_mono.py
The `avpop_mono` module brings in a new model for AvPop that has strictly monotonic behavior w/r/t mass and sSFR. The new model has 12 parameters, compared to 18 in `avpop_flex`.
Here's a plot of the default model:
The plots below visualize the behavior of models selected from a few randomly generated points in `u_param` space. Notice that everything is always monotonic. There are unit tests in this PR that enforce this strict monotonic behavior for hundreds of randomly generated models.
@gbeltzmo I
> New AvPop model with strictly monotonic behavior w/r/t mass and sSFR

- diffsky/dustpop/avpop_mono.py
In the previous implementation brought in with PR #56, the parameters `avpop_params.suav_logsm_x0` and `avpop_params.suav_logssfr_x0` had no effect, since a global variable was accidentally used instead of their influence.
> Fix bug in get_av_from_avpop_params_scalar

- diffsky/burstpop/freqburst_mono.py
- diffsky/burstpop/tests/test_freqburst_mono.py
The `freqburst_mono` module brings in a new model for AvPop that has strictly monotonic behavior w/r/t mass and sSFR. The new model has 6 parameters, compared to 9 in `freqburst`.
Here's a plot of the default model:
The plots below visualize the behavior of models selected from a few randomly generated points in u_param space. Notice that everything is always monotonic. Notice also that the trends with stellar mass are reversed here relative to the model implemented in #56 - here, burst frequency is enforced to _increase_ with decreasing stellar mass. There are unit tests in this PR that enforce this strict monotonic behavior for hundreds of randomly generated models.
> Fqburst mono

- diffsky/systematics/ssp_errors.py
- diffsky/systematics/tests/test_ssp_errors.py
This PR brings in a simple empirical model capturing misspecification in the SSP template SEDs. The `ssp_errors.py` module implements a model for a multiplicative factor that is applied to the SSP SEDs. This is not a galaxy--halo model ingredient, since this model doesn't care about halos, only possible errors in the SSPs, so I put this code in a new `systematics` directory. These effects would get applied very early in our prediction pipeline, creating an alternate flux table that would get passed as input to the halos.
There are an countless ways the SSP templates could be wrong. This simple model adopts a sigmoid function of wavelength. 
If our SSP SEDs are systematically incorrect in a way that varies smoothly and monotonically with wavelength in the optical, this model should do a …
> Add model of SSP systematics

- .github/workflows/tests.yml
- .github/workflows/tests_cron.yml
- diffsky/__init__.py
- diffsky/mass_functions/mc_diffmah_tpeak.py
- diffsky/mass_functions/mc_subhalo_catalog.py
- diffsky/mass_functions/tests/test_mc_diffmah_tpeak.py
- docs/source/demo_diffmahpop_t_peak.ipynb
- docs/source/demos.rst
- docs/source/index.rst
This PR adds a new Monte Carlo generator of subhalo catalogs based on the new version of DiffmahPop. The PR includes an RTD doctest notebook demonstrating how to use the generator by making the plot below.
> Monte Carlo generators for `t_peak`-based Diffmah

- diffsky/tests/test_utils.py
- diffsky/utils.py
This PR brings in a function that computes a penalty for models whose stellar-to-halo-mass relation differ from some input target SMHM. The code is really just a convenience wrapper around a couple of triweight kernels with hyperparameters that have tuned to reasonable values for the typical prior we want to assume for the SMHM.
For the _width_ of the kernel, I just tuned the triweight square well to have a width of ~0.5dex. The _magnitude_ of the penalty function is not set to any default value, but is a required input to this function. I think this should probably ideally be ~1-10x the un-penalized value of the typical loss, which of course will depend on whatever are the other target sumstats in the analysis, and so tuning this hyper-parameter might require a little experimentation.
> Add kernel for prior on SMHM

- diffsky/data_loaders/load_hacc_cores.py
The `get_infall_time_indices` function assigns `-1` to cores that were never satellites prior to the time of observation, `z_obs`. Previously, this condition was calculated by checking whether the core was always a satellite _for all of cosmic time_, rather than for all times up until `z_obs`. This PR fixes this error.
> Fix bug in calculation of infall times for high-redshift halos

- diffsky/burstpop/fburstpop.py
- diffsky/burstpop/freqburst_mono.py
- diffsky/burstpop/tests/test_fburstpop.py
- diffsky/burstpop/tests/test_freqburst_mono.py
- diffsky/dustpop/avpop_mono.py
- diffsky/dustpop/tests/test_avpop_mono.py
Introduce new convenience parameters to use when implementing zero dust and/or zero burstiness:
- `ZERODUST_AVPOP_PARAMS` for `avpop_mono.py`
- `ZEROBURST_FREQBURST_PARAMS` for `freqburst.py`
- `ZEROBURST_FBURSTPOP_PARAMS` for `fburstpop.py`
Also include some basic tests that these parameters produce the expected behavior.
> Introduce ZERODUST_AVPOP_PARAMS for `avpop_mono.py`

- diffsky/burstpop/freqburst_mono.py
This PR mimics what was done in #92 but now for `freqburst_mono.py`. This module already had monotonic kernels, however I noticed that the bounds were set to far too high, in light of recent results about how impactful burstiness is on massive galaxies especially. I'll show a comparison of plots of the old and new default models below, which shows that the new default model has much milder burst frequency than the previous model.
Probably more importantly than the change to the default behavior, I think the new bounds on the burst frequency variable should result in much less extreme models of burstiness.
@gbeltzmo
> Adjust bounds of freq-burst model and change default behavior

- diffsky/cosmos_utils/cosmos_mstar_model.py
- diffsky/cosmos_utils/tests/test_cosmos_mstar_model.py
This PR brings in a simple linear model that approximate the relationship between `griz` apparent magnitudes and redshift, and the stellar mass in the LePhare catalog. This could be a useful way to define the stellar mass of our target data, since the modeled stellar mass is computed from pure photometry, and would have no reliance upon the SEDs assumed by LePhare. (Well, _less_ reliance anyway, since we are still using the `photoz`).
This plot shows that the approximate stellar mass is more or less unbiased with ~0.33 dex of scatter about the LePhare value.
This plot shows the stellar mass function looks basically the same
Here are a few plots of color histograms based on this pure-photometry stellar mass.
And here are a few color-color diagrams
> Add new module to define stellar mass for cosmos

- diffsky/mass_functions/mc_diffmah_tpeak.py
- diffsky/mass_functions/tests/test_mc_diffmah_tpeak.py
The `mc_subhalos` function generates a Monte Carlo realization of a subhalo population. Previously, the quantity `subcat.subs_lgmhost_ult_inf` was assigned to be `subcat.tpeak`, a bug leading to grossly unrealistic values for host halo mass. This PR fixes the bug.
> Fix bug in subs_lgmhost_ult_inf

- diffsky/mass_functions/mc_diffmah_tpeak.py
- diffsky/mass_functions/tests/test_mc_diffmah_tpeak.py
- diffsky/mass_functions/upweighting/tests/test_mc_gen_upweighting.py
- diffsky/mc_diffsky.py
- diffsky/tests/test_mc_diffsky.py
- docs/source/demo_diffmahpop_t_peak.ipynb
Add Monte Carlo generator of central galaxies.
This PR also breaks the API of the `mc_subhalos` function. The order of the positional arguments used to be `mc_subhalos(ran_key, lgmp_min, z_obs, **kwargs)`, but now the signature is `mc_subhalos(ran_key, z_obs, **kwargs)`. The reason for the change is to support an input argument `hosts_logmh_at_z`, as opposed to generating a volume-complete sample of halos down to some limiting mass.
> Add Monte Carlo generator of central galaxies

- diffsky/burstpop/diffqburstpop_mono.py
- diffsky/burstpop/tests/test_diffqburstpop_mono.py
For a while now, we have been using monotonic versions of ingredients for burst frequency (`freqburst_mono`) and burst intensity (`fburstpop_mono`). However, there has been no unified burstiness model that includes these components. This PR implements a new `diffqburstpop_mono.py` model that is the exact analog of `diffqburstpop.py`, but using the monotonic ingredients. This will eliminate the need to implement code that unifies these ingredients within the diffdesi repo.
> Incorporate `_mono` burst models into unified burstpop model

- diffsky/experimental/monte_carlo_lightcone_redshifts.py
- diffsky/experimental/tests/test_monte_carlo_lightcone_redshifts.py
New `mc_lightcone_redshift` function generates a sample of redshifts from a lightcone spanning `(z_min, z_max)` assuming a constant comoving number density of points (i.e., passive evolution). The MC generator works by inverse transformation sampling:
1. calculate the comoving cosmological volume on a redshift grid `z_table` that spans the input range, `V_table = (4π/3)Rcom(z_table)**3`
2. define `CDF_table` as the unit-normalized cumulative sum of the volume grid
3. draw uniform randoms, `u`
4. interpolate `u` on the lookup table relation `CDF_table--z_table` to get a random redshift
@gbeltzmo I'm putting this new function in the experimental directory for now. We can use this when we put together a Monte Carlo generator of lightcone photometry.
> Add Monte Carlo generator of lightcone redshifts

- diffsky/experimental/mc_lightcone_halos.py
- diffsky/experimental/tests/test_mc_lightcone_halos.py
This PR brings in code to generate Monte Carlo realizations of central galaxy photometry on a lightcone. The photometry only includes smooth SFH, no burstiness, no dust, and no SSP errors. Here are a couple of example plots made with the new code.
> Monte Carlo central galaxies on a lightcone

- diffsky/burstpop/freqburst_mono.py
- diffsky/burstpop/tests/test_freqburst_mono.py
The updated burstpop model now looks like the plot below
@gbeltzmo
> Update burst frequency model to be even less conservative

- diffsky/burstpop/fburstpop_mono.py
Bringing into main updates to `fburstpop_mono.py` bounds. This PR makes the `burstpop_mono` model more flexible, allowing for more extreme burstiness models.
> fburstpop_mono bounds updates

- diffsky/data_loaders/hacc_utils/data_validation/tests/test_validate_lc_cores.py
- diffsky/data_loaders/hacc_utils/data_validation/validate_lc_cores.py
Add unit test of `core_tag` uniqueness and `top_host_tag` agreement with `diffsky.utils.crossmatch`.
Note that with the current code, for lightcone files in which there is a repeated value of `core_tag` (about 2% of the files), we skip the test of `top_host_tag` agreement with `diffsky.utils.crossmatch`. The reason is that in this case, the bookkeeping is a little complicated since `diffsky.utils.crossmatch` does not run on arrays with a repeated entry for the `core_tag`.
> Add unit test of `core_tag` uniqueness and `top_host_tag` agreement with `diffsky.utils.crossmatch`

- diffsky/data_loaders/hacc_utils/lc_mock_production.py
- diffsky/data_loaders/hacc_utils/load_lc_cf.py
The value of `scale_factor` stored in the `lc_cores` files does not include the effect of peculiar velocity, so the column named `z_obs` in the output Diffsky mocks was misnamed. This PR fixes this for future mocks.
> `z_obs --> z_true`

- diffsky/experimental/diagnostics/check_smhm.py
- diffsky/experimental/diagnostics/tests/test_check_smhm.py
This PR brings in code to make this plot that we can use to assess the results from the lightcone-based fits
The calling signature is simple:
`fig = check_smhm.plot_diffstarpop_insitu_smhm(diffstarpop_params, diffstarpop_params2)
`
In the figure above, both dashed and solid curves were generated with `DEFAULT_DIFFSTARPOP_PARAMS`, and so the dashed are right on top of the solid.
@AlanPearl - the results of your lightcone-based optimizations are computed as a flat `u_param` array. But you can extract the `diffstarpop_params` using the two-line pattern shown [here](https://github.com/ArgonneCPAC/diffsky/blob/83b78dd4e077f609d627ec1a32844e1c5ed66e29/diffsky/experimental/lc_phot_kern.py#L352).
> Add check_smhm validation test

- diffsky/mass_functions/hmf_model.py
In the docstring to `hmf_model.predict_differential_hmf`, it was previously stated that the returned quantity is the base-10 log of the differential HMF. This PR corrects the docstring to read that the returned quantity is the differential HMF itself (no log).
> Fix error in docstring

- diffsky/data_loaders/hacc_utils/lightcone_utils.py
Add an assert statement into the code that runs the cross-match
> Require `core_tag` to match between coreforest and lc-cores
